spring:
  datasource:
    url: jdbc:mysql://localhost:3306/INFORMAR_O_NOME_DO_BANCO?useSSL=false&serverTimezone=America/Sao_Paulo
    username: INFOMAR_O_NOME_DO_USUÁRIO_DO_BANCO
    password: INFOMAR_A_SENHA_DO_USUÁRIO_DO_BANCO
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect